### PR TITLE
Upgrade dependencies and improve DX

### LINKED ISSUE #321: Upgrade TypeScript setup and improve DX in `uxpin-merge-cli`
## Goals

- Remove `tslint` dependency that is deprecated since 2019 🙀 (see https://github.com/palantir/tslint/issues/4534)
- Use [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) instead and setup rules similar to the existing one
- Use Prettier to format the code
- Set up TS to write idiomatic TypeScript as much as possible

## Details

The main problem I found when checking the code is that our setup forces us to declare the types of any variable in any single line in of the code base, even if it's not needed because of TypeScript capacity to infer types.

It makes the code verbose and redundant.

It seems to come from this rule: https://github.com/UXPin/tslint-config-uxpin/blob/master/tslint.json

We should try to set up an environment that is up-to-date and as standard as possible.

## Action plan

- Remove `tslint`
- Setup `typescript-eslint`
- Setup Prettier
- Update Make commands
- Clean the code using eslint `--fix` parameter
- Ensure nothing is broken!

We may need commit hooks to trigger linting.

### PR DESCRIPTION
**Pull request by michaelrambeau**
## Goal

This is the first attempt to improve the DX, standardize the setup and upgrade some of the dependencies (fix #321)

Check list:

- [x] Remove `tslint` (deprecated) and its rules that force us to declare the type of every single dummy variable instead of relying on type inference
- [x] Add `TypeScript ESLint`
- [x] Setup Prettier
- [x] Upgrade Make commands
- [x] Format files with the new settings
- [x] Upgrade to Node.js 16 (the current LTS version)

About ESLint setup: in order to avoid having to fix any TS error introduced by the new setup, I added some rules that show up as "warnings" instead of errors to prevent the build from failing.
These rules should be removed and the errors fixed in a separate PR.

The following points would be handled in a separate PR:

- [ ] Upgrade `typescript`
- [ ] Upgrade Webpack from 4 to 5?

## Make commands

`make check`  is run on the CI before building the code.
Before `make check` used to check both code style rules and types using `tslint`.

Now `make check` calls 2 different sub-commands in a row:

- `make check-lint-errors`: ESLint applies its standard rules about the rules + the formatting rules from Prettier
- `make check-types` checks the static types

When developing use `make check-types-watch` to get instant feedback about the types.

## How to check

- Switch to Node.js 16
- `cd uxpin-merge-cli`
- `yarn install`
- `make check`

Try to edit a file removing a `;` for example: the error should show up in the IDE, if ESLint is setup correctly in your IDE.

Then try the "Format file" command: the missing `;` should be added automatically by Prettier.

### CODE REVIEW

**Comment by michaelrambeau** [comment]
## Formatting files with the new rules

I've run `make check-fix` to fix automatically files according to new rules.

image

**Comment by michaelrambeau** [comment]
## Testing

It seems that not all tests are passing on the `master` branch:

```
Test Suites: 5 failed, 73 passed, 78 total
Tests:       5 failed, 5 skipped, 486 passed, 496 total
Snapshots:   3 passed, 3 total
Time:        116.07 s
```

We may have to fix some tests related to dates as all errors seem to be similar:

```diff
-         "value": "1997-02-01T01:01:01.001Z",
+         "value": "1997-01-31T16:01:01.001Z",
```

**Comment by Evomatic** [comment]
Functionality of the CLI seems to be good! (a few failing tests though) Here are some of the things I tested

1. The added `make` commands.
2. pushing a git library to uxpin
3. pushing a git library version such as `branch` or `tag`
4. deleting a git library version
5. experimental mode
6. Ran unit tests
- I think you mentioned this above, the failing tests for me, also include the dates

```diff
-         "value": "1997-02-01T01:01:01.001Z",
+         "value": "1997-01-31T16:01:01.001Z",
```

and a few others:

```diff
 FAIL  src/steps/serialization/vcs/repositories/git/util/__tests__/getCurrentBranch.test.ts
  ● getCurrentBranch › should return current branch name

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return master if not given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return master if not given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return master if not given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return the real branch name only if given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return the real branch name only if given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

  ● getCurrentBranch › new branch › should return the real branch name only if given an override

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

 FAIL  src/steps/serialization/vcs/repositories/__tests__/getRepositoryAdapter.test.ts
  ● getRepositoryAdapter › should return GitRepositoryAdapter for git repository

    Could not determine version control system for your repository!

      17 |   }
      18 | 
    > 19 |   throw new Error('Could not determine version control system for your repository!');
         |         ^
      20 | }
      21 | 

      at Object.<anonymous> (src/steps/serialization/vcs/repositories/getRepositoryAdapter.ts:19:9)
      at fulfilled (node_modules/tslib/tslib.js:104:62)

 FAIL  src/steps/serialization/vcs/repositories/git/util/__tests__/getMovedFiles.test.ts
  ● getMovedFiles › should get map of moved files

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

 FAIL  src/steps/serialization/vcs/repositories/git/util/__tests__/isGitRepository.test.ts
  ● itGitRepository › should return true if directory belongs to a valid git repository

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      11 | 
      12 |     // then
    > 13 |     expect(isGit).toBe(true);
         |                   ^
      14 |   });
      15 | 
      16 |   it('should return false if directory is not a valid git repository', async () => {

      at src/steps/serialization/vcs/repositories/git/util/__tests__/isGitRepository.test.ts:13:19
      at fulfilled (node_modules/tslib/tslib.js:104:62)

 FAIL  src/steps/serialization/vcs/repositories/git/util/__tests__/getLatestCommit.test.ts
  ● getLatestCommit › should get info about latest commit

    spawn /bin/sh ENOENT

      10 |     exec(command, options, (error: Error | null, stdout: string, stderr: string): void => {
      11 |       if (error) {
    > 12 |         const execError: ExecError = new ExecError(error.message);
         |                                      ^
      13 |         execError.stdout = stdout;
      14 |         execError.stderr = stderr;
      15 | 

      at src/utils/child_process/execAsync.ts:12:38

 FAIL  src/steps/serialization/vcs/repositories/git/util/__tests__/isCommit.test.ts
  ● isCommit › should return true if commit exists

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      13 |     // when
      14 |     // then
    > 15 |     expect(await isCommit(path, 'd914edd5f97cadb284f7f47b783106c86fe430d9')).toBe(true);
         |                                                                              ^
      16 |   });
      17 | 
      18 |   it('should return false if commit does not exist', async () => {

      at src/steps/serialization/vcs/repositories/git/util/__tests__/isCommit.test.ts:15:78
      at fulfilled (node_modules/tslib/tslib.js:104:62)
```

I was tried on master branch as well and was getting the same failed tests, so it is probably "OK" for now...Of course we don't want to have any failing tests! 😅

**Review by Evomatic — APPROVED** [review]
👨‍💻

**Comment by michaelrambeau** [comment]
Thank you for having checked Evan!

I have added an extra commit to make the unit test pass in local, too.

As I mentioned above, there was a problem because we were checking a date object created using the local settings: `new Date(1997, 1, 1, 1, 1, 1, 1),`, which does not represent the same time depending on where the code runs.


So now **unit** tests should work. However **integration** tests seem to be pretty tricky and solving them looks like a challenge of its own. I'm linking the document you have found: https://github.com/UXPin/uxpin-merge-tools/blob/master/packages/uxpin-merge-cli/DEVELOPMENT.md

**Comment by robhil** [comment]
> ## Formatting files with the new rules
> All TypeScript files from the following folders have been fixed automatically by ESLint (using the `--fix` argument):
> 
> * `src`
> * `test`
> * `__mocks__`
> 
> This PR, despite its huge size should not include any manual change in the code, the only change being related to [this commit](https://github.com/UXPin/uxpin-merge-tools/pull/323/commits/e7528f9643cb7bd43d3ab45281acb5cd0dcf5106) where I used the `?.` syntax to make a line more compact and ensure a `ts-ignore` comment can apply to the next line.
> 
> Question number 1 for @robhil
> 
> Is there a reason why we have a `.uxpin-merge` folder that is not ignored by Git here?
> 
> https://github.com/UXPin/uxpin-merge-tools/tree/master/packages/uxpin-merge-cli/test/resources/designSystems/watchingChanges/.uxpin-merge

.uxpin-merge is generated by cli I think it should be ignored 🤔

**Comment by robhil** [comment]
On the branch, I had to fix a test that was failing on CircleCI, changing a number to a literal (see below) but I'm not sure I did the right move, what do you think @robhil ?

Interesting, we have to check how it looks in editor, type is changed maybe there will be wrong control in UI 🤔 
Are you able to test it?

**Comment by michaelrambeau** [comment]
## `typeof` investigation

OK Rob I have investigated about the failing test I had to fix.

- React component: https://github.com/UXPin/uxpin-merge-tools/blob/ea558781f85ef3a7cb8a2ca80bb941b71cb33dd3/packages/uxpin-merge-cli/test/resources/components/typescript/ClassWithKeyOfTypeOfOperatorInType.tsx#L2
- Test:https://github.com/UXPin/uxpin-merge-tools/blob/a100b4087c031edd3d64406889cf9631e2ca7bab/packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/__tests__/serializeTSComponent.test.ts#L1021

It's about the behavior of `typeof` with primitives in TypeScript (note: JS run time has its own`typeof` operator, it's different)

When you do `typeof` of a variable declared as a `const`, TypeScript considers it's the number 5, it's not any number, because you cannot change its value, so it's right.

However if you use `let` instead of `const`, the inferred type is a number.

Check [this TS playground](https://www.typescriptlang.org/play?ts=4.0.5#code/MYewdgzgLgBAbgQwDYFcCmBGGBeGBWAbgFgAoUqATwAc0YAVatAeQDMAFAJxCq10ppAt4ydBmJkSLFGGBQAluBhIQAcwAUADwBc9Rq07cMAShgBvUjBihIIJGgB0y9RqPiAvqVJO1AFhMB6fxg0Di4OABoYOVgIAAsQFCQAExgAI1ooWNowFABbdI58Twk7WERUNAAmHHxxfloGGn0uKghqvkZBYQrKghhAmDAQAHcoqAByCBgEQbyCgEIgA) where I put the following code

```ts
const value1 = 5;

type TypeOfProp1 = typeof value1; // the type is the number 5

function log(x: TypeOfProp1) {
  console.log(x);
}

log(4) // TS error, it should be the number 5

let value2 = 5;
type TypeOfProps2 = typeof value2; // now it's a number!
```

**Review by robhil — APPROVED** [review]

**Pull request merged**
