### PR TITLE
Feature/147 support storybook

### PR DESCRIPTION
**Pull request by vados-xenon**
Work on the support for storybook with the Merge CLI

### CODE REVIEW

**Comment by vados-xenon** [comment]
Hey @itsderek23 I just tested the instructions in 7845314 locally , you *should* be able to follow them to the tee and get things working locally (use `yarn link` as necessary and I personally manually softly link `uxpin-merge` w/ `ln -s` when doing local development). Update-and-reload is also working.

I used [react-bootstrap](https://github.com/uxpin-merge/react-bootstrap-merge/) for my testing of these instructions (in particular the `Button` component), but you may want to use one of the other merge-enabled example repos.

Also, [found a 404](https://www.uxpin.com/docs/merge/creating-a-uxpin-merge-library) (from [the using react docs](https://www.uxpin.com/docs/merge/using-react.js-components#how-to-access-merge))

**Comment by itsderek23** [comment]
Great stuff!

@matthewchigira - is this something you or Sam could take for a spin and try? Would like to have you exposed to this in some part as it develops.

**Comment by matthewchigira** [comment]
> Great stuff!
> 
> @matthewchigira - is this something you or Sam could take for a spin and try? Would like to have you exposed to this in some part as it develops.

Hey, yeah sure would love to take a look!

**Comment by naohiro-t** [comment]
I'll work on this in https://github.com/UXPin/uxpin-merge-tools/pull/236 , so closing this for now.

**Pull request closed without merging**
