### PR TITLE
Replace deprecated 'opn' package with 'open'

### LINKED ISSUE #218: Experimental Mode not working with Windows (and WSL)
### Issue
When using Merge in Windows using the WSL, experimental mode has a problem.

In the URL that it generates and opens, it will insert the ^ character after your port number. This results in the page not being able to load.

image

### Workaround
The workaround is to manually delete the ^ character from the URL in the browser and that enables the page to load. N.B. this does not affect the normal `uxpin-merge push` command.

### Idea for fix
If we can't prevent this character from being inserted (perhaps it comes from a bug in WSL), then we can just manually strip out ^ characters from [final generated string](https://github.com/UXPin/uxpin-merge-tools/blob/9e1a941de7b9e7d6440533d598296a7d2ffdd72b/packages/uxpin-merge-cli/src/steps/experimentation/app/getAPPExperimentationRemoteURL.ts#L12).

### PR DESCRIPTION
**Pull request by matthewchigira**
Closes #218 

See [comment](https://github.com/UXPin/uxpin-merge-tools/issues/218#issuecomment-736294244) for explanation.

### CODE REVIEW

**Comment by matthewchigira** [comment]
So we needed to replace `opn` package with `open` in order to fix our issue with Windows/WSL. We have tested that this works on our Windows machine here at the office.

However, when I updated `open`, I also had to bump up the TypeScript version a little, which introduced a few new type errors. @vados-xenon would you be able to check [this commit](https://github.com/UXPin/uxpin-merge-tools/pull/220/commits/e746a2e322d7fde2c9c39f0da5ea263a911a3f1a) in particular for me? This commit has those TypeScript errors that I had to fix, just want to check I haven't inadvertently broken something!

**Comment by matthewchigira** [comment]
FYI dev version of the built npm package is [here](https://www.npmjs.com/package/@uxpin/merge-cli/v/2.7.1-dev-218.2)

**Comment by vados-xenon** [comment]
@matthewchigira  that specific commit looks good to me, will go through and do a full review as well

**Comment by vados-xenon** [comment]
hey @matthewchigira I just realized I don't actually have a windows machine to test this with -- I'm going to approve this though

**Review by vados-xenon — APPROVED** [review]

**Pull request merged**
